import 'package:get/get.dart';

class ProductsController extends GetxController {
  final products = [
    {
      'title': 'Excee Sneakers',
      'imageProduct': 'assets/img/shoes_1.png',
      'bgColor': '#C6E2F1',
      'offer': '30%',
      'fevaritColor': '#41BB92',
      'rating': '4.5',
      'price': '500',
    },
    {
      'title': 'Nike Air Max 200',
      'imageProduct': 'assets/img/shoes_2.png',
      'color': '#F9A1DA',
      'bgColor': '#F9A1DA',
      'offer': '60%',
      'fevaritColor': '#00B8FF',
      'rating': '4',
      'price': '400',
    },
    {
      'title': 'Nike Air Max 200',
      'imageProduct': 'assets/img/shoes_3.png',
      'color': '#F9A1DA',
      'bgColor': '#B738F0',
      'offer': '50%',
      'fevaritColor': '#F53678',
      'rating': '5',
      'price': '300',
    },
    {
      'title': 'Nike Air Max Pro',
      'imageProduct': 'assets/img/shoes_4.png',
      'color': '#F9A1DA',
      'bgColor': '#FDD446',
      'offer': '10%',
      'fevaritColor': '#B738F0',
      'rating': '3',
      'price': '250',
    },
    {
      'title': 'Nike Air Max 300',
      'imageProduct': 'assets/img/shoes_5.png',
      'color': '#F9A1DA',
      'bgColor': '#FF8000',
      'offer': '50%',
      'fevaritColor': '#41BB92',
      'rating': '4',
      'price': '360',
    },
    {
      'title': 'Nike Air Max 200',
      'imageProduct': 'assets/img/shoes_6.png',
      'color': '#F9A1DA',
      'bgColor': '#9A6E8B',
      'offer': '50%',
      'fevaritColor': '#FFD700',
      'rating': '5',
      'price': '300',
    },
    {
      'title': 'Nike Air Max 10',
      'imageProduct': 'assets/img/shoes_7.png',
      'color': '#F9A1DA',
      'bgColor': '#B1B4E2',
      'offer': '15%',
      'fevaritColor': '#AAE7CA',
      'rating': '3.5',
      'price': '256',
    },
  ];
}
